sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zavanton/spider-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zavanton/spider-test npm run test

after_success:
  - docker build -t zavanton/spider-client ./client
  - docker build -t zavanton/spider-server ./server
  - docker build -t zavanton/spider-worker ./worker
  - docker build -t zavanton/spider-nginx ./nginx
  - echo $HUB_PASS | docker login -u $HUB_ID --password-stdin
  - docker push zavanton/spider-client
  - docker push zavanton/spider-server
  - docker push zavanton/spider-worker
  - docker push zavanton/spider-nginx


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'batman'
  env: 'Batman-env'
  bucket_name: 'elasticbeanstalk-us-east-2-565447122202'
  bucket_path: 'docker-batman'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

