sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zavanton/spider-test -f ./client/Dockerfile ./client

script:
  - docker run -e CI=true zavanton/spider-test npm run test

