sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t zavanton/superman-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zavanton/superman-test npm run test

after_success:
  - docker build -t zavanton/superman-client ./client
  - docker build -t zavanton/superman-server ./server
  - docker build -t zavanton/superman-worker ./worker
  - docker build -t zavanton/superman-nginx ./nginx
  - echo $HUB_PASS | docker login -u $HUB_ID --password-stdin
  - docker push zavanton/superman-client
  - docker push zavanton/superman-server
  - docker push zavanton/superman-worker
  - docker push zavanton/superman-nginx


deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'superman'
  env: 'Superman-env'
  bucket_name: 'elasticbeanstalk-us-east-2-565447122202'
  bucket_path: 'docker-superman'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

